services:
  nginx:
    build: ./nginx
    ports:
      - "1024:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mariadb

  mariadb:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  wordpress_data:
  mariadb_data: