services:
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    build: ./wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - password
    restart: unless-stopped

  mariadb:
    build: ./mariadb
    image: mariadb
    env_file:
      - .env
    secrets:
      - password
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress
    
secrets:
  password:
    file: ../secrets/password.txt