services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build: ./mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  wordpress_data:
  mariadb_data: